### ISSUE TITLE
Add coding style check

### ISSUE THREAD

**Issue by peter279k** [EFTEC/RouteOne#2]
To be consistency with other repositories (such as BladeOne package) on this organisation, this package should require the coding style.

I think we can consider this [.php_cs](https://github.com/EFTEC/BladeOne/blob/master/.php_cs) coding style setting.

**Comment by jorgecc** [comment]
My coding style is the style of phpstorm that it is incompatible with php_cs

And since both are neither standard, then I stick with phpstorm default style, because that style works out of the box.  I can add php_cs to phpstorm but sheesh, I tried and it was a waste of time for an arbitrary style (php_cs).

**Comment by peter279k** [comment]
Hi @jorgecc, thanks for your reply.

Do you have any coding style tool about phpstorm style?

And it can be automatic to do coding style check during Travis CI build.
